# Generated by Django 4.0 on 2024-05-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explanation',
            field=models.BooleanField(default=False),
        ),
    ]
